=== MaggotIISS/T5Min/_XML/Practice/0/Address.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/Address.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE address SYSTEM "Address.dtd">

    <address>
    ...
    </address>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT address (name|street|town|region|postcode|country)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT name (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT street (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT town (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT region (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT postcode (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT country (#PCDATA)>

=== MaggotIISS/T5Min/_XML/Practice/0/Address.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE address SYSTEM "Address.dtd">
<!--
http://www.w3.org/TR/xml

http://www.w3.org/TR/xslt

http://www.w3schools.com/xml/default.asp

http://www.w3schools.com/schema/default.asp

http://www.w3schools.com/xsl/default.asp

http://www.w3schools.com/webservices/default.asp

UK postal data
Postal address letters are sent to
<name id=""></name>
<street id=""></street>
<town id=""></town>
<region id=""></region>
<postcode id=""></postcode>
<country id=""></country>
-->
<address>
  <name>Mark Ferguson</name>
  <street>83 Admiralty Road</street>
  <town>GREAT YARMOUTH</town>
  <region>Norfolk</region>
  <postcode>NR303DX</postcode>
  <country>UK</country>

  <name>Debi Ferguson</name>
  <street>83 Admiralty Road</street>
  <town>GREAT YARMOUTH</town>
  <region>Norfolk</region>
  <postcode>NR303DX</postcode>
  <country>UK</country>
</address>
